package main

import (
	"fmt"
	"os"

	"go.zoe.im/x/cli"

	"go.zoe.im/gopkg/cmd"
)

// DO NOT EDIT THIS FILE DIRECTLY. These are build-time constants
// set through ‘scripts/gen-ldflags.go’.
var (
	// GOPATH - GOPATH value at the time of build.
	GOPATH = ""

	// GOROOT - GOROOT value at the time of build.
	GOROOT = ""

	// Go get development tag.
	goGetTag = "DEVELOPMENT.GOGET"

	// Version - version time.RFC3339.
	Version = goGetTag
	// ReleaseTag - release tag in TAG.%Y-%m-%dT%H-%M-%SZ.
	ReleaseTag = goGetTag
	// CommitID - latest commit id.
	CommitID = goGetTag
	// ShortCommitID - first 12 characters from CommitID.
	ShortCommitID = CommitID[:12]
)

func main() {
	if err := cmd.Run(
		cli.Version(ReleaseTag),
	); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
